[package]
name = "localex-ipc"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { path = "../common/" }
anyhow = "1.0.86"
ciborium = "0.2.2"
nix = { version = "0.29.0", features = ["user"] }
tokio = { version = "1", features = ["full"] }
tracing = "0.1.40"
serde = { version = "1.0", features = ["derive"] }
async-trait = "0.1.81"
uuid = { version = "1.10.0", features = ["v4", "fast-rng", "macro-diagnostics"] }
bytes = "1.7.1"
