[package]
name = "localex-ipc"
version = "0.1.0"
edition = "2021"

[dependencies]
protocol = { path = "../protocol/" }
anyhow = "1.0.86"
ciborium = "0.2.2"
nix = "0.29.0"
tokio = { version = "1.38.0", features = ["full"] }
tracing = "0.1.40"
serde = { version = "1.0", features = ["derive"] }
async-trait = "0.1.81"
