[workspace]
resolver = "2"
members = [
  "packages/common",
  "packages/localex",
  "packages/localex-daemon",
  "packages/localex-gui",
  "packages/localex-ipc",
  "packages/localex-tui",
  "packages/logger",
]
