[package]
name = "localex"
version = "0.1.0"
edition = "2021"

[dependencies]
libp2p = { version = "0.53", features = ["tcp", "tls", "dns", "tokio", "noise", "yamux", "websocket", "ping", "macros", "quic", "mdns"] }
futures = "0.3.21"
tokio = { version = "1", features = ["full"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
anyhow = "1.0.86"
secret-service = { version = "4.0.0", features = ["rt-tokio-crypto-rust"] }
