[package]
name = "network"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { path = "../common/"}
libp2p = { version = "0.54.0", features = ["tcp", "tokio", "noise", "yamux", "macros", "gossipsub", "mdns", "request-response", "cbor", "quic", "tls"] }
tokio = { version = "1", features = ["full"] }
anyhow = "1.0.86"
