[package]
name = "localex"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.21"
tokio = { version = "1", features = ["full"] }
anyhow = "1.0.86"
clap = { version = "4.5.9", features = ["derive"] }
tracing = "0.1.40"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = 'abort'
