[package]
name = "localex"
version = "0.1.0"
edition = "2021"

[dependencies]
libp2p = { git = "https://github.com/libp2p/rust-libp2p.git", commit = "c19c1409824a68586c3779729329040a554f12db", features = ["tcp", "tokio", "noise", "yamux", "macros", "gossipsub", "mdns", "request-response", "cbor", "quic"] }
futures = "0.3.21"
tokio = { version = "1", features = ["full"] }
anyhow = "1.0.86"
secret-service = { version = "4.0.0", features = ["rt-tokio-crypto-rust"] }
serde = { version = "1", features = ["derive"] }
ciborium = "0.2.2"
serde_repr = "0.1.19"
hostname = "0.4.0"
ratatui = "0.27.0"
crossterm = { version = "0.27.0", features = ["serde", "event-stream"] }
clap = { version = "4.5.9", features = ["derive"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
tracing-appender = "0.2.3"
dirs = "5.0.1"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = 'abort'
