[package]
name = "protocol"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { path = "../common/" }
network = { path = "../network/" }
libp2p = { version = "0.54.0", features = ["tcp", "tokio", "noise", "yamux", "macros", "gossipsub", "mdns", "request-response", "cbor", "quic", "tls"] }
futures = "0.3.21"
tokio = { version = "1", features = ["full"] }
anyhow = "1.0.86"
serde = { version = "1.0", features = ["derive"]}
tracing = "0.1.40"
async-trait = "0.1.81"
uuid = { version = "1.10.0", features = ["v4", "fast-rng", "macro-diagnostics"] }
async-compression = { version = "0.4.12", features = ["tokio", "zstd"] }
bimap = "0.6.3"
