[package]
name = "protocol"
version = "0.1.0"
edition = "2021"

[dependencies]
libp2p = { git = "https://github.com/libp2p/rust-libp2p.git", commit = "8e28edf69a5f25d1d919962a70fa32203b48f8dd", features = ["serde"] }
serde = { version = "1.0", features = ["derive"]}
serde_repr = "0.1.19"
