[package]
name = "localax"
version = "0.1.0"
edition = "2021"

[dependencies]
protocol = { path = "../protocol/" }
network = { path = "../network/" }
common = { path = "../common/" }
logger = { path = "../logger/" }
anyhow = "1.0.86"
futures = "0.3.21"
tokio = { version = "1", features = ["full"] }
libp2p = { git = "https://github.com/libp2p/rust-libp2p.git", rev = "1617abb3bfcf3e8663568e90a8fc4009aef04ba9", features = ["tcp", "tokio", "noise", "yamux", "macros", "gossipsub", "mdns", "request-response", "cbor", "quic", "tls"] }
uniffi = { version = "0.28.0", features = ["tokio"] }
thiserror = "1.0.63"
async-trait = "0.1.81"

[build-dependencies]
uniffi = { version = "0.28.0", features = ["build"] }

[lib]
crate-type = ["cdylib"]
name="localax"
