[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
bit-vec = "0.8.0"
dirs = "5.0.1"
libp2p = { version = "0.54.0", features = ["serde"] }
serde = { version = "1.0", features = ["derive"]}
serde_repr = "0.1.19"
tokio = { version = "1.39.3", features = ["full"] }
uuid = { version = "1.10.0", features = ["v4", "fast-rng", "macro-diagnostics"] }
