[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
libp2p = { version = "0.54.0", features = ["serde"] }
serde = { version = "1.0", features = ["derive"]}
serde_repr = "0.1.19"
