[package]
name = "localex-daemon"
version = "0.1.0"
edition = "2021"

[dependencies]
network = { path = "../network/" }
common = { path = "../common/" }
localex-ipc = { path = "../localex-ipc/" }
logger = { path = "../logger/" }
libp2p = { git = "https://github.com/libp2p/rust-libp2p.git", rev = "1617abb3bfcf3e8663568e90a8fc4009aef04ba9", features = ["tcp", "tokio", "noise", "yamux", "macros", "gossipsub", "mdns", "request-response", "cbor", "quic", "tls"] }
futures = "0.3.21"
tokio = { version = "1", features = ["full"] }
anyhow = "1.0.86"
secret-service = { version = "4.0.0", features = ["rt-tokio-crypto-rust"] }
serde = { version = "1.0", features = ["derive"]}
hostname = "0.4.0"
clap = { version = "4.5.9", features = ["derive"] }
tracing = "0.1.40"
dirs = "5.0.1"
ctrlc = "3.4.4"
ciborium = "0.2.2"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = 'abort'
