[package]
name = "localex-daemon"
version = "0.1.0"
edition = "2021"

[dependencies]
protocol = { path = "../protocol/" }
localex-ipc = { path = "../localex-ipc/" }
logger = { path = "../logger/" }
libp2p = { git = "https://github.com/libp2p/rust-libp2p.git", commit = "8e28edf69a5f25d1d919962a70fa32203b48f8dd", features = ["tcp", "tokio", "noise", "yamux", "macros", "gossipsub", "mdns", "request-response", "cbor", "quic"] }
futures = "0.3.21"
tokio = { version = "1", features = ["full"] }
anyhow = "1.0.86"
secret-service = { version = "4.0.0", features = ["rt-tokio-crypto-rust"] }
serde = { version = "1.0", features = ["derive"]}
hostname = "0.4.0"
clap = { version = "4.5.9", features = ["derive"] }
tracing = "0.1.40"
dirs = "5.0.1"
