[package]
name = "localex-daemon"
version = "0.1.0"
edition = "2021"

[dependencies]
protocol = { path = "../protocol/" }
network = { path = "../network/" }
common = { path = "../common/" }
localex-ipc = { path = "../localex-ipc/" }
logger = { path = "../logger/" }
futures = "0.3.21"
tokio = { version = "1", features = ["full"] }
anyhow = "1.0.86"
secret-service = { version = "4.0.0", features = ["rt-tokio-crypto-rust"] }
serde = { version = "1.0", features = ["derive"]}
hostname = "0.4.0"
clap = { version = "4.5.9", features = ["derive"] }
tracing = "0.1.40"
dirs = "5.0.1"
ctrlc = "3.4.4"
ciborium = "0.2.2"
async-trait = "0.1.81"
async-compression = { version = "0.4.12", features = ["tokio", "zstd"] }
uuid = { version = "1.10.0", features = ["v4", "fast-rng", "macro-diagnostics"] }
bimap = "0.6.3"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = 'abort'
